### PR TITLE
Updates azure api gems

### PR DESCRIPTION
**Pull request by gmmeyer**
Updates azure api gems so that I no longer encounter issue #423

### CODE REVIEW

**Comment by NimishaS** [comment]
@gmmeyer , we had pinned the versions of those azure gems because we had encountered several backward incompatible changes when we updated last. It started breaking the existing functionality of `knife-azure`.
We'll test all the existing functionality and then upgrade the version.

**Comment by gmmeyer** [comment]
@NimishaS thank you! knife-azure no longer works for me with either the chefdk or with a vanilla, clean install of Ruby

**Comment by dheerajd-msys** [comment]
I have verified the functionalities for `knife-azure ARM` with latest gems. They doesn't seem to work and are breaking. So we are working on to fix the issue.
Verified for :`knife azurerm server create`

**Comment by dheerajd-msys** [comment]
I have verified the functionalities for `knife-azure ARM` with latest gems. They doesn't seem to work and are breaking. So we are working on to fix the issue.
Verified for below functionalities :

**Comment by dheerajd-msys** [comment]
I have verified the functionalities for ` knife-azure ARM `with latest gems. They doesn't seem to work and are breaking. So we are working on to fix the issue.

**Comment by NimishaS** [comment]
Closing this PR as we have merged https://github.com/chef/knife-azure/pull/425.

@gmmeyer these changes are not released yet, but you can work around using following steps for time being:
```
1. gem uninstall knife-azure      #This uninstalls the current installed version
2. git clone https://github.com/chef/knife-azure
3. cd knife-azure
4. gem build knife-azure.gemspec
5, gem install knife-azure-1.7.0.gem
```

**Pull request closed without merging**
