### PR TITLE
Allow using relative path for config file

### PR DESCRIPTION
**Pull request by tas50**
The example in the readme for knife-azure doesn't actually work.

knife azure image list
ERROR: Unable to find file - ~/.azure_settings.publishsettings

Expand the provided path first so we can find the file.

### CODE REVIEW

**Comment by tas50** [comment]
@NimishaS any thoughts on getting this one merged?

**Comment by NimishaS** [comment]
@tas50 we'll take this up.

**Comment by Vasu1105** [comment]
@tas50  what if the user keeps is publish settings file in any other folder ?knife[:azure_publish_settings_file] options accepts the path to your publish settings file https://github.com/chef/knife-azure/blob/master/docs/configuration.md#asm-mode

**Comment by Vasu1105** [comment]
@NimishaS  +1

**Comment by NimishaS** [comment]
The changes are cherry-picked and merged here https://github.com/chef/knife-azure/pull/392.

Thanks for contribution @tas50.

**Pull request closed without merging**
