### PR TITLE
Added code for Windows platform to read azure creds from azureProfile if publish_settings file not available.

### PR DESCRIPTION
**Pull request by Aliasgar16**
In-progress.

### CODE REVIEW

**Comment by Aliasgar16** [comment]
Testing is completed. RSpecs are pending.

**Comment by Aliasgar16** [comment]
Completed with RSpecs and hence with the overall development and testing.

**Comment by NimishaS** [comment]
@andrewelizondo , @adamedx, please review this.

**Comment by adamedx** [comment]
Looks good, but can we have a READEME update also? In the [configuration](https://github.com/chef/knife-azure#configuration) section of the README, we should point out that the azure profile can be used, and then refer to Microsoft's docs on configuring that via the Azure xplat tools or PowerShell tools.

**Comment by andrewelizondo** [comment]
Other than what @adamedx mentioned about the documentation this looks solid. :shipit:

**Comment by Aliasgar16** [comment]
@adamedx Updated README to point out the usage of azure profile.

**Comment by andrewelizondo** [comment]
:shipit:

**Pull request merged**
