### PR TITLE
Added support for ohai_hints for cloud-api protocol in ARM.

### PR DESCRIPTION
**Pull request by Aliasgar16**
In-progress.

### CODE REVIEW

**Comment by Aliasgar16** [comment]
Development is completed. Testing is pending.

**Comment by Aliasgar16** [comment]
Testing is done. RSpecs is pending.

**Comment by Aliasgar16** [comment]
RSpecs is done. Re-based the branch.

**Comment by andrewelizondo** [comment]
:+1: after the conflicts are resolved

**Comment by Aliasgar16** [comment]
Resolved the conflicts.

**Pull request merged**
