### PR TITLE
KNIFE-481 - Virtual machine state 'provisioning' not reached after 5 minutes.

### PR DESCRIPTION
**Pull request by elmundio87**
Added a new parameter to configure the previously hardcoded timeout in wait_for_virtual_machine_state

Details: https://tickets.opscode.com/browse/KNIFE-481

### CODE REVIEW

**Comment by invisibletank** [comment]
Hi.  Azure often still has problems timing out after 5 minutes waiting for provisioning while running knife azure. I know I'm not the only one running into this.  Does someone with write access plan on merging these changes from last summer?  Or has this issue been taken care of in another ticket?  I figure asking here first is better than wasting time redoing someone else's work.  Thanks! :)

**Comment by prelegalwonder** [comment]
+1 here. My knife-azure provision commands fail about half the time.

**Comment by siddheshwar-more** [comment]
Need rebase with master. 

We will open new pull request to have similar kind of options for extension as well- Refer  https://github.com/chef/knife-azure/blob/master/lib/chef/knife/azure_server_create.rb#L254-L268

**Comment by adamedx** [comment]
@siddheshwar-more, can you create a new branch with this rebased and submit a new PR? That might be the fastest way to get this in so we can do a release.

**Comment by adamedx** [comment]
Folks, let's use this PR: https://github.com/chef/knife-azure/pull/155.

**Comment by adamedx** [comment]
Fixed with #185 and released in version 1.4.0 -- thank you @elmundio87.

**Pull request closed without merging**
