### PR TITLE
Updating gemspec to reflect knife-windows update from 1.9.6 to 3.0.3 …

### PR DESCRIPTION
**Pull request by jasonh-edfi**
### Description

Updates knife-azure gemspec to depend on knife-windows version 3.x+ and higher as released in May 2019.

### Issues Resolved

https://github.com/MicrosoftDocs/azure-docs/issues/24474

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by Vasu1105** [comment]
@jasonh-edfi we are updated knife-azure to use Chef-15. knife-azure was dependent on  knife-windows for winrm communication but with this update we know will require knife-windows. There is [PR](https://github.com/chef/knife-azure/pull/500) to support Chef-15 with knife-azure which we will be merging soon. @btm  any thoughts on this ?

**Comment by jasonh-edfi** [comment]
@Vasu1105 sounds good - if an update is soon pending and no longer needed or explicitly defined, please feel free to close without merging,  I have temp fix and will pick up final fix once update released.

**Comment by tas50** [comment]
@jasonh-edfi I'm going to close this out now since I merged in #500. I'll be releasing the 2.0 version of this gem this morning. Sorry for the wait.

**Comment by jasonh-edfi** [comment]
@tas50 Sounds good and glad to hear about the 2.0 release.  Looking forward to trying out against an Azure deployment to help resume work there.  Curious how this could be picked up, I tried this morning `chef gem install knife-azure` and still picking up 1.9.0?

**Comment by jasonh-edfi** [comment]
@tas50 anything I can do to pick up manually?  Still not seeing in https://rubygems.org/gems/knife-azure?

**Comment by jasonh-edfi** [comment]
@tas50 thank you!!!

**Comment by tas50** [comment]
I think we had a promote fail. All is good now

**Pull request closed without merging**
