### PR TITLE
Issue 205: External/Public Load Balancer support

### PR DESCRIPTION
**Pull request by aiman-alsari**
Allowing TCP and UDP endpoint param string to also specify a load balancer set name and probe path. This is for load balancing public IPs - not internal ones.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by siddheshwar-more** [comment]
Re-based with #231

**Comment by siddheshwar-more** [comment]
@aiman-alsari 

Could you please sign CLA. Refer following links to sign CLA-
https://github.com/chef/chef/blob/master/CONTRIBUTING.md
https://supermarket.getchef.com/icla-signatures/new

**Comment by aiman-alsari** [comment]
Hi @siddheshwar-more , I already have....

Perhaps I need to recreate the pull-request?

**Comment by aiman-alsari** [comment]
image

**Comment by adamedx** [comment]
Ah, we do have your CLA, can't trust the curry bot on this one, thank you @aiman-alsari.

**Pull request merged**
