### PR TITLE
OC 8384 windows ssh support

### PR DESCRIPTION
**Pull request by muktaa**

### CODE REVIEW

**Comment by thommay** [comment]
@muktaa @smurawski hey, I assume we'd still like to take this PR?

**Comment by muktaa** [comment]
@thommay - yes, the PR still seems valid, but might need rebase.
@NimishaS - FYI

**Comment by smurawski** [comment]
@thommay @muktaa Definitely.

**Comment by stuartpreston** [comment]
Closing this - as the changes are no longer valid.

**Pull request closed without merging**
